"""System tray icon (RF-34, ADR-012) - best-effort, non-blocking.

`build_icon` assembles a `pystray.Icon` with a menu (status, pause/resume, edit
configuration, quit); `TrayIcon` runs it on a separate worker thread, leaving
Tkinter as the exclusive owner of the main thread (ADR-006). Any failure while
building or starting the icon (missing graphical backend, GNOME/Wayland without
a tray extension, etc.) is isolated: a *warning* is logged and the agent keeps
running without the icon, just like `notify/toast.py` and `geoloc.py`.
"""

from __future__ import annotations

import logging
import os
import subprocess
import sys
import threading
from collections.abc import Callable
from pathlib import Path

from PIL import Image
from pystray import Icon, Menu, MenuItem

from .agent_state import AgentState
from .i18n import DEFAULT_LOCALE, t

_ICON_FILE_NAME = "tray_icon.png"


def default_icon_path() -> Path:
    """Path to the icon PNG packaged alongside the package."""
    return Path(__file__).parent / "assets" / _ICON_FILE_NAME


def _open_command(path: Path) -> list[str] | None:
    """OS command to open `path` with its associated app; `None` = use `os.startfile`."""
    if sys.platform == "darwin":
        return ["open", str(path)]
    if sys.platform == "win32":
        return None
    return ["xdg-open", str(path)]


def open_config(path: Path, *, logger: logging.Logger | None = None) -> None:
    """Opens `config.toml` with the OS's associated app; creates it if missing (RF-34)."""
    log = logger or logging.getLogger("vigia_eew.tray")
    try:
        if not path.exists():
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(
                "# Generated by Vigía-eew - see config.toml.example in the repo for\n"
                "# all available options.\n",
                encoding="utf-8",
            )
        command = _open_command(path)
        if command is None:
            os.startfile(path)  # type: ignore[attr-defined]  # only exists on Windows
        else:
            subprocess.Popen(command)
    except OSError as exc:
        log.warning("tray_could_not_open_config detail=%s", exc)


def build_icon(
    *,
    state: AgentState,
    paused: Callable[[], bool],
    toggle_pause: Callable[[], None],
    edit_config: Callable[[], None],
    exit: Callable[[], None],
    icon_path: Path | None = None,
    locale_code: str = DEFAULT_LOCALE,
) -> Icon:
    """Assembles the `pystray.Icon` with its menu; does not start it (see `TrayIcon`)."""
    image = Image.open(icon_path or default_icon_path())

    def _status_text(_item: MenuItem) -> str:
        key = "tray_ws_connected" if state.ws_connected else "tray_ws_reconnecting"
        return t(key, locale_code)

    def _last_alert_text(_item: MenuItem) -> str:
        return state.last_alert or t("tray_no_alerts_yet", locale_code)

    def _pause_text(_item: MenuItem) -> str:
        key = "tray_resume_notifications" if paused() else "tray_pause_notifications"
        return t(key, locale_code)

    menu = Menu(
        MenuItem(_status_text, action=None, enabled=False),
        MenuItem(_last_alert_text, action=None, enabled=False),
        Menu.SEPARATOR,
        MenuItem(_pause_text, action=lambda icon, item: toggle_pause()),
        MenuItem(t("tray_edit_config", locale_code), action=lambda icon, item: edit_config()),
        Menu.SEPARATOR,
        MenuItem(t("tray_quit", locale_code), action=lambda icon, item: exit()),
    )
    return Icon("vigia-eew", icon=image, title="Vigía-eew", menu=menu)


class TrayIcon:
    """Runs the `pystray.Icon` on a separate worker thread (best-effort)."""

    def __init__(self, icon: Icon, *, logger: logging.Logger | None = None) -> None:
        self._icon = icon
        self._thread: threading.Thread | None = None
        self._log = logger or logging.getLogger("vigia_eew.tray")

    def start(self) -> None:
        """Starts the icon on a separate thread."""
        self._thread = threading.Thread(target=self._run, daemon=True)
        self._thread.start()

    def _run(self) -> None:
        # Runs on the icon's thread: any failure in the graphical backend (no
        # display, GNOME/Wayland without extension, etc.) is logged here and
        # not propagated - the agent keeps running without the icon (RF-34).
        try:
            self._icon.run()
        except Exception as exc:  # noqa: BLE001 - deliberate best-effort
            self._log.warning("tray_run_error type=%s detail=%s", type(exc).__name__, exc)

    def stop(self) -> None:
        """Stops the icon and waits for its thread to finish."""
        try:
            self._icon.stop()
        except Exception as exc:  # noqa: BLE001 - must not prevent agent shutdown
            self._log.warning("tray_stop_error type=%s detail=%s", type(exc).__name__, exc)
        if self._thread is not None:
            self._thread.join(timeout=2.0)
